### ISSUE TITLE
[Improvement Suggestion] Adjust Margin Footer.

### ISSUE THREAD

**Issue by aldamr01** [bandungpy/pycon.id#39]
Ada beberapa issue, terkait tampilan di web browser saya di halaman sponsor, yaitu footer dan main content tidak ada margin nya, jadi tampilanya terlihat seperti ini.

<img width="1422" alt="image" src="https://github.com/bandungpy/pycon.id/assets/32734712/a10ee9a0-7145-4c4a-affd-98e33de1be12">

mungkin bisa di improve dengan menambahkan margin agar terlihat agak joss seperti gambar berikut
<img width="1422" alt="image" src="https://github.com/bandungpy/pycon.id/assets/32734712/5d9d8717-b7b7-45e8-a990-49f7e3d5136c">

Thankyou.

**Comment by ridhof** [comment]
hi @jeeehaan can you help with this issue? it's regarding css styling. I think you can do it!

**Comment by jeeehaan** [comment]
Thank you for mentioning me mas @ridhof. I will fix it soon.
